#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#xrandr --output DP-0 --primary --mode 2560x1440 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --right-of DP-0



#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-0 -d 1 2 3 4
bspc monitor HDMI-1 -d 5 6 7 8

bspc config border_width         3
bspc config window_gap          12
bspc config focused_border_color "#595959"
bspc config normal_border_color "#000000"
bspc config active_border_color "#000000"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart applications
sxhkd &
nitrogen --restore &
dunst &
polybar left &
polybar right &
picom &
